{% set name = "editor" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/editor-{{ version }}.tar.gz
  sha256: 979b25e3f7e0386af4478e7392ecb99e6c16a42db7c4336d6b16658fa0449fb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - runs
    - xmod

test:
  imports:
    - editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rec/editor
  summary: 🖋 Open the default text editor 🖋
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
