{% set name = "editor" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/editor-{{ version }}.tar.gz
  sha256: b07e1bbcb8b33f05c2e6ed3ce77ee9756354ada840a18aad7c0536d967fe4c0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - runs
    - xmod

test:
  imports:
    - editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rec/editor
  summary: 🖋 Open the default text editor 🖋
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
